### ISSUE TITLE
setup @idfind on twitter

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/idfind#14]
We need to peruse the confirmation link, so that the e-mail address associated with the account can be confirmed. Then we can login as a developer at dev.twitter.com , and setup the idfind application. I've resent the confirmation email for convenience.

**Comment by markmacgillivray** [comment]
I clicked the confirmation link, it asked me to login, but was not
sure the password. however, the link has been clicked, should be fine.

On Sat, Feb 11, 2012 at 9:11 PM, emanuil-tolev
reply@reply.github.com
wrote:

**Comment by emanuil-tolev** [comment]
Apparently not :/ (sorry, this shouldn't be so much of a bother!!). I've sent an information e-mail around.

**Comment by markmacgillivray** [comment]
Done, account is confirmed.

**Comment by emanuil-tolev** [comment]
Account set up on dev.twitter.com, application created, e-mail with info sent to @markmacgillivray and @richard-jones .
